### ISSUE TITLE
calculation of the soil probe

### ISSUE THREAD

**Issue by beckmx** [fredriknk/SoilSense#1]
Hello there, I noticed you have indications that the probe is a 70pf value, I am starting a project as well, and if you dont mind I was wondering how you measure this, did you measure it with a multimeter? also I noticed that from the fork you made the probe had 2 resistors and 1 "variable_capacitor", what made you change from that approach into yours?

**Comment by fredriknk** [comment]
Ill answer more later. The 70 pf value is a coplanar capacitor calculation based on the width/length/separation of the  copper trace probes with the dielectric capacity of water. The main difference between this and the original is that I use an 80mhz mems oscillator which should make the sensor less sensitive towards salinity. There are some errors in the design untill this fall (conflicting pin selections and trying to power the mems with a grip, in essence don't use the pins on the side of the board! They are all specialized) which I won't have time to fix

**Comment by fredriknk** [comment]
If you need a working solution asap, this is a good repo https://github.com/rbaron/b-parasite , but it is low frequency (a few mhz) so salinity buildup will affect it but it has a very good codebase.
